-- ==============================================================================
-- 🍃 HORTIFRUTI DA JANETE - SCRIPT SQL COMPLETO PARA O SUPABASE
-- Execute este script no SQL Editor do painel Supabase (https://supabase.com/dashboard)
-- ==============================================================================

-- 1. Criação da tabela de PEDIDOS com as colunas exatas
CREATE TABLE IF NOT EXISTS pedidos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_nome TEXT,
  telefone TEXT,
  cliente_telefone TEXT,
  endereco TEXT,
  bairro TEXT,
  taxa_entrega NUMERIC DEFAULT 0,
  itens JSONB DEFAULT '[]'::jsonb,
  total NUMERIC DEFAULT 0,
  status TEXT DEFAULT 'Pendente',
  tipo_entrega TEXT DEFAULT 'entrega',
  forma_pagamento TEXT DEFAULT 'pix',
  pagamento TEXT DEFAULT 'PIX',
  observacoes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Garante compatibilidade de colunas caso a tabela já exista
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS telefone TEXT;
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS endereco TEXT;
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS bairro TEXT;
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS taxa_entrega NUMERIC DEFAULT 0;
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS itens JSONB DEFAULT '[]'::jsonb;
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS total NUMERIC DEFAULT 0;
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'Pendente';
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS cliente_nome TEXT;

-- 2. Criação da tabela de TAXAS DE ENTREGA (por Bairro)
CREATE TABLE IF NOT EXISTS taxas_entrega (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bairro TEXT UNIQUE NOT NULL,
  valor NUMERIC NOT NULL DEFAULT 5.00,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Inserção das taxas de entrega iniciais dos bairros (caso ainda não existam)
INSERT INTO taxas_entrega (bairro, valor)
VALUES 
  ('Centro', 5.00),
  ('Jardim Primavera', 6.00),
  ('Vila Nova', 7.00),
  ('Planalto', 8.00),
  ('Bela Vista', 6.50),
  ('Alto do Cruzeiro', 7.50)
ON CONFLICT (bairro) DO NOTHING;

-- ==============================================================================
-- ⚡ LIBERAÇÃO DE PERMISSÕES (ROW LEVEL SECURITY)
-- ==============================================================================

-- Libera acesso total para ler, criar e atualizar pedidos
ALTER TABLE pedidos DISABLE ROW LEVEL SECURITY;

-- Libera acesso total para ler e gerenciar taxas de entrega
ALTER TABLE taxas_entrega DISABLE ROW LEVEL SECURITY;

-- ==============================================================================
-- 🔔 TRANSMISSÃO DE NOTIFICAÇÕES EM TEMPO REAL (REALTIME)
-- ==============================================================================

-- Garante que a tabela 'pedidos' transmita notificações ao vivo para o Painel Admin
ALTER PUBLICATION supabase_realtime ADD TABLE pedidos;

-- Garante que a tabela 'taxas_entrega' também sincronize em tempo real
ALTER PUBLICATION supabase_realtime ADD TABLE taxas_entrega;
